namespace DataAccess.Enum
{
    public enum UserActionType
    {
        Unknown = 0,
        USER_ASKED_CHATBOT = 1,
        USER_VIEWED_EVENT = 2,
        USER_SEARCHED_EVENT = 3,
        USER_ASKED_EVENT_DETAILS = 4,
        USER_ASKED_REGISTRATION_STATUS = 5,
        USER_ASKED_WHY_CANT_FIND_EVENT = 6,
        USER_ASKED_ELIGIBILITY = 7,
        USER_REGISTERED_EVENT = 8,
        USER_CANCELLED_EVENT = 9,
        USER_INTERESTED_IN_CATEGORY = 10,
        USER_ASKED_EVENT_SCHEDULE = 11,
        Update = 12,
        Delete = 13,
        Approve = 14,
        Reject = 15,
        Cancel = 16,
        SoftDelete = 17,
        Restore = 18,
        Submit = 19,
        Publish = 20,
        Sync = 21,
        AddMember = 22,
        RemoveMember = 23,
        Create = 24,
        USER_JOINED_WAITLIST = 25,
        USER_RESPONDED_OFFER = 26,
        USER_SUBMITTED_FEEDBACK = 27,
        View = 2,
        Register = 8,
        CheckIn = 28,
        CheckOut = 29,
        Login = 30,
        Logout = 31,
        AccountRegister = 32,
        ChangePassword = 33,
        Export = 34,
        Import = 35
    }
}
